---
name: "Generate THIRDPARTY"
description: "Generate license listing of third party dependencies in Artichoke Ruby"

inputs:
  artichoke_ref:
    required: true
    type: string
  target_triple:
    required: true
    type: string

outputs:
  third_party_licenses:
    description: Plaintext listing of third party licenses
    value: ${{ steps.generate_third_party.outputs.third_party_licenses }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: artichoke/generate_third_party
        path: generate_third_party

    - name: Clone Artichoke
      uses: actions/checkout@v3
      with:
        repository: artichoke/artichoke
        ref: ${{ inputs.artichoke_ref }}
        path: "artichoke-${{ inputs.artichoke_ref }}"

    - name: Install cargo-about
      shell: bash
      run: cargo install --debug --locked cargo-about

    - name: Install Ruby toolchain
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ".ruby-version"
        bundler-cache: true
        working-directory: generate_third_party

    - name: Generate THIRDPARTY
      id: generate_third_party
      shell: bash
      working-directory: generate_third_party
      run: |
        third_party="$(bundle exec generate-third-party-text-file-single-target \
          "${{ inputs.target_triple }}" \
          "../artichoke-${{ inputs.artichoke_ref }}/Cargo.toml"
        )"
        third_party="${third_party//'%'/'%25'}"
        third_party="${third_party//$'\n'/'%0A'}"
        third_party="${third_party//$'\r'/'%0D'}"
        echo "::set-output name=third_party_licenses::$third_party"
