---
name: "Generate THIRDPARTY"
description: "Generate license listing of third party dependencies in Artichoke Ruby"

inputs:
  artichoke_ref:
    required: true
    type: string
  target_triple:
    required: true
    type: string
  output_file:
    required: true
    type: string
  github_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Clone Artichoke
      uses: actions/checkout@v3
      with:
        repository: artichoke/artichoke
        ref: ${{ inputs.artichoke_ref }}
        path: "generate-third-party-artichoke-${{ inputs.artichoke_ref }}"

    - name: Install generate_third_party
      shell: bash
      run: |
        gem build generate_third_party.gemspec
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo gem install generate_third_party-*.gem
        else
          gem install generate_third_party-*.gem
        fi
      working-directory: ${{ github.action_path }}

    - name: Install cargo-about
      shell: bash
      run: install-cargo-about "${{ runner.os }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Generate THIRDPARTY
      shell: bash
      run: |
        generate-third-party-text-file-single-target \
          --target "${{ inputs.target_triple }}" \
          "${{ github.workspace }}/generate-third-party-artichoke-${{ inputs.artichoke_ref }}/Cargo.toml" \
          > "${{ inputs.output_file }}"

    - name: Cleanup
      shell: bash
      run: rm -rf "${{ github.workspace }}/generate-third-party-artichoke-${{ inputs.artichoke_ref }}"
