---
name: "Generate THIRDPARTY"
description: "Generate license listing of third party dependencies in Artichoke Ruby"

branding:
  icon: "book"
  color: "green"

inputs:
  artichoke_ref:
    description: Git ref to checkout in artichoke/artichoke repository.
    required: true
  target_triple:
    description: LLVM target triple used to select platform-specific dependencies.
    required: true
  output_file:
    description: Path to output file.
    required: true
  github_token:
    description: Github token from Actions environment.
    required: true

runs:
  using: "composite"
  steps:
    # https://github.com/actions/checkout/issues/135
    - name: Setup git line ending checkout behavior
      shell: bash
      if: runner.os == 'Windows'
      run: |
        git config --system core.autocrlf false
        git config --system core.eol lf

    # `actions/checkout` only permits checkouts within the `github.workspace`
    # directory. See https://github.com/actions/checkout/issues/197.
    - name: Set paths
      shell: bash
      id: paths
      run: |
        mkdir -p "$TEMP_PREFIX"
        artichoke_repository_path="${TEMP_PREFIX}/artichoke@${ARTICHOKE_REF}"
        echo "CLEANUP_PATH=${TEMP_PREFIX}" >> "$GITHUB_OUTPUT"
        echo "ARTICHOKE_REPOSITORY_PATH=${artichoke_repository_path}" >> "$GITHUB_OUTPUT"
        echo "CARGO_MANIFEST_PATH=${artichoke_repository_path}/Cargo.toml" >> "$GITHUB_OUTPUT"
      env:
        TEMP_PREFIX: ${{ github.workspace }}/${{ github.action }}-${{ github.run_id }}-${{ github.run_attempt }}
        ARTICHOKE_REF: ${{ inputs.artichoke_ref }}

    - name: Clone Artichoke
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: artichoke/artichoke
        ref: ${{ inputs.artichoke_ref }}
        path: ${{ steps.paths.outputs.ARTICHOKE_REPOSITORY_PATH }}

    - name: Install generate_third_party
      shell: bash
      run: |
        gem build generate_third_party.gemspec
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo gem install generate_third_party-1.15.0.gem
        else
          gem install generate_third_party-1.15.0.gem
        fi
      working-directory: ${{ github.action_path }}

    - name: Install cargo-about
      shell: bash
      run: install-cargo-about --platform "${{ runner.os }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: cargo about --version
      shell: bash
      run: cargo about --version

    - name: Update stable rust
      shell: bash
      run: rustup update stable

    - name: Generate THIRDPARTY
      shell: bash
      run: |
        generate-third-party-text-file-single-target --target "$TARGET_TRIPLE" "$CARGO_MANIFEST_PATH" > "$OUTPUT_FILE"
      env:
        RUST_TOOLCHAIN: stable
        TARGET_TRIPLE: ${{ inputs.target_triple }}
        CARGO_MANIFEST_PATH: ${{ steps.paths.outputs.CARGO_MANIFEST_PATH }}
        OUTPUT_FILE: ${{ inputs.output_file }}

    - name: Cleanup
      shell: bash
      run: rm -rf "$CLEANUP_PATH"
      env:
        CLEANUP_PATH: ${{ steps.paths.outputs.CLEANUP_PATH }}
